// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetHash() {
  return window['go']['main']['App']['GetHash']();
}

export function GetProfileIndex() {
  return window['go']['main']['App']['GetProfileIndex']();
}

export function Login(arg1) {
  return window['go']['main']['App']['Login'](arg1);
}
