// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetHash():Promise<string>;

export function GetProfileIndex():Promise<main.ProfileIndex>;

export function Login(arg1:string):Promise<void>;
