// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetEntry(arg1:string,arg2:number):Promise<main.Entry>;

export function GetHash():Promise<string>;

export function GetProfileIndex():Promise<main.ProfileIndex>;

export function ListEntries(arg1:string):Promise<Array<main.EntrySummary>>;

export function Login(arg1:string):Promise<void>;

export function SaveEntry(arg1:string,arg2:string,arg3:string):Promise<number>;
