// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProfile(arg1, arg2) {
  return window['go']['main']['App']['AddProfile'](arg1, arg2);
}

export function DeleteEntry(arg1, arg2) {
  return window['go']['main']['App']['DeleteEntry'](arg1, arg2);
}

export function DeleteProfile(arg1, arg2) {
  return window['go']['main']['App']['DeleteProfile'](arg1, arg2);
}

export function GetEntry(arg1, arg2) {
  return window['go']['main']['App']['GetEntry'](arg1, arg2);
}

export function GetProfileIndex() {
  return window['go']['main']['App']['GetProfileIndex']();
}

export function ListEntries(arg1) {
  return window['go']['main']['App']['ListEntries'](arg1);
}

export function LockProfile() {
  return window['go']['main']['App']['LockProfile']();
}

export function SaveEntry(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveEntry'](arg1, arg2, arg3);
}

export function UnlockProfile(arg1, arg2) {
  return window['go']['main']['App']['UnlockProfile'](arg1, arg2);
}
