// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AddElabftwInstance(profileUUID: string, siteURL: string, apiKey: string, verifyTLS: boolean): $CancellablePromise<number> {
    return $Call.ByID(2830032626, profileUUID, siteURL, apiKey, verifyTLS);
}

/**
 * AddProfile creates a new profile with a passphrase-derived encryption key.
 */
export function AddProfile(displayName: string, passphrase: string): $CancellablePromise<$models.ProfileIndex | null> {
    return $Call.ByID(1200490073, displayName, passphrase).then(($result: any) => {
        return $$createType1($result);
    });
}

export function DeleteElabftwInstance(profileUUID: string, id: number): $CancellablePromise<void> {
    return $Call.ByID(1750796384, profileUUID, id);
}

export function DeleteEntry(profileUUID: string, id: number): $CancellablePromise<void> {
    return $Call.ByID(3442753994, profileUUID, id);
}

/**
 * DeleteProfile deletes a profile after verifying its passphrase.
 * It does not require the profile to already be unlocked.
 */
export function DeleteProfile(profileUUID: string, passphrase: string): $CancellablePromise<$models.ProfileIndex | null> {
    return $Call.ByID(2457157279, profileUUID, passphrase).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * DeleteUpload removes a locally stored upload.
 * 
 * Each upload record belongs to one entry
 * The encrypted file is stored by its SHA-256 hash and may therefore be
 * shared by multiple upload records
 * The physical file is removed only after the final database reference to that
 * hash has been deleted.
 */
export function DeleteUpload(profileUUID: string, entryID: number, uploadID: number): $CancellablePromise<void> {
    return $Call.ByID(3551449719, profileUUID, entryID, uploadID);
}

/**
 * DownloadUpload decrypts an upload and exports it to a location selected by
 * the user. An empty returned path means that the user cancelled the dialog!
 */
export function DownloadUpload(profileUUID: string, entryID: number, uploadID: number): $CancellablePromise<string> {
    return $Call.ByID(753691208, profileUUID, entryID, uploadID);
}

/**
 *  ---------- INFO ENDPOINT ----------
 */
export function FetchElabftwInfo(profileUUID: string, instanceID: number): $CancellablePromise<$models.ElabftwInfo | null> {
    return $Call.ByID(1280266864, profileUUID, instanceID).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetEntry(profileUUID: string, id: number): $CancellablePromise<$models.Entry | null> {
    return $Call.ByID(471730233, profileUUID, id).then(($result: any) => {
        return $$createType5($result);
    });
}

export function GetProfileIndex(): $CancellablePromise<$models.ProfileIndex | null> {
    return $Call.ByID(313063036).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ImportUpload(profileUUID: string, entryID: number, sourcePath: string): $CancellablePromise<$models.StoredUpload | null> {
    return $Call.ByID(4036065165, profileUUID, entryID, sourcePath).then(($result: any) => {
        return $$createType7($result);
    });
}

export function ListElabftwInstances(profileUUID: string): $CancellablePromise<$models.ElabftwInstance[]> {
    return $Call.ByID(2516082466, profileUUID).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * Titles are stored encrypted, so decrypt them before returning the summaries to frontend.
 */
export function ListEntries(profileUUID: string): $CancellablePromise<$models.EntrySummary[]> {
    return $Call.ByID(3068416191, profileUUID).then(($result: any) => {
        return $$createType11($result);
    });
}

export function ListEntryRemoteLinks(profileUUID: string, entryID: number): $CancellablePromise<$models.EntryRemoteLink[]> {
    return $Call.ByID(1152126526, profileUUID, entryID).then(($result: any) => {
        return $$createType13($result);
    });
}

export function ListEntryUploads(profileUUID: string, entryID: number): $CancellablePromise<$models.StoredUpload[]> {
    return $Call.ByID(816579067, profileUUID, entryID).then(($result: any) => {
        return $$createType14($result);
    });
}

/**
 * LockProfile clears the in-memory session state.
 * After this, profile-scoped actions reject reads/writes until UnlockProfile
 * succeeds again.
 */
export function LockProfile(): $CancellablePromise<void> {
    return $Call.ByID(1608678519);
}

export function PushAllEntriesToElabftw(profileUUID: string, instanceID: number, entityType: string, force: boolean): $CancellablePromise<$models.PushEntryResult[]> {
    return $Call.ByID(3318953334, profileUUID, instanceID, entityType, force).then(($result: any) => {
        return $$createType16($result);
    });
}

export function PushEntryToElabftw(profileUUID: string, entryID: number, instanceID: number, entityType: string, force: boolean): $CancellablePromise<$models.PushEntryResult | null> {
    return $Call.ByID(2235037999, profileUUID, entryID, instanceID, entityType, force).then(($result: any) => {
        return $$createType17($result);
    });
}

export function SaveEntry(profileUUID: string, title: string, body: string): $CancellablePromise<number> {
    return $Call.ByID(3296818692, profileUUID, title, body);
}

export function SelectFile(): $CancellablePromise<string> {
    return $Call.ByID(2427571203);
}

/**
 * UnlockProfile verifies the passphrase by decrypting the profile's encrypted
 * verifier. On success, the derived key is kept in memory and used to
 * encrypt/decrypt entry contents for this profile only.
 */
export function UnlockProfile(profileUUID: string, passphrase: string): $CancellablePromise<void> {
    return $Call.ByID(1831918630, profileUUID, passphrase);
}

export function UpdateElabftwInstance(profileUUID: string, id: number, siteURL: string, apiKey: string, verifyTLS: boolean): $CancellablePromise<void> {
    return $Call.ByID(3424358178, profileUUID, id, siteURL, apiKey, verifyTLS);
}

export function UpdateEntry(profileUUID: string, id: number, title: string, body: string): $CancellablePromise<void> {
    return $Call.ByID(2925690800, profileUUID, id, title, body);
}

// Private type creation functions
const $$createType0 = $models.ProfileIndex.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.ElabftwInfo.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $models.Entry.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $models.StoredUpload.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $models.ElabftwInstance.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = $models.EntrySummary.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = $models.EntryRemoteLink.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = $Create.Array($$createType6);
const $$createType15 = $models.PushEntryResult.createFrom;
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = $Create.Nullable($$createType15);
