// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ElabftwInfo {
    "raw": { [_ in string]?: any };

    /** Creates a new ElabftwInfo instance. */
    constructor($$source: Partial<ElabftwInfo> = {}) {
        if (!("raw" in $$source)) {
            this["raw"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ElabftwInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ElabftwInfo {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("raw" in $$parsedSource) {
            $$parsedSource["raw"] = $$createField0_0($$parsedSource["raw"]);
        }
        return new ElabftwInfo($$parsedSource as Partial<ElabftwInfo>);
    }
}

export class ElabftwInstance {
    "id": number;
    "siteUrl": string;
    "apiKey"?: string;
    "verifyTls": boolean;

    /** Creates a new ElabftwInstance instance. */
    constructor($$source: Partial<ElabftwInstance> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("siteUrl" in $$source)) {
            this["siteUrl"] = "";
        }
        if (!("verifyTls" in $$source)) {
            this["verifyTls"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ElabftwInstance instance from a string or object.
     */
    static createFrom($$source: any = {}): ElabftwInstance {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ElabftwInstance($$parsedSource as Partial<ElabftwInstance>);
    }
}

export class Entry {
    "id": number;
    "title": string;
    "body": string;
    "createdAt": string;
    "modifiedAt": string;

    /** Creates a new Entry instance. */
    constructor($$source: Partial<Entry> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("body" in $$source)) {
            this["body"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }
        if (!("modifiedAt" in $$source)) {
            this["modifiedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Entry instance from a string or object.
     */
    static createFrom($$source: any = {}): Entry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Entry($$parsedSource as Partial<Entry>);
    }
}

export class EntryRemoteLink {
    "localId": number;
    "instanceId": number;
    "siteUrl": string;
    "remoteId": number;
    "type": string;
    "url": string;

    /** Creates a new EntryRemoteLink instance. */
    constructor($$source: Partial<EntryRemoteLink> = {}) {
        if (!("localId" in $$source)) {
            this["localId"] = 0;
        }
        if (!("instanceId" in $$source)) {
            this["instanceId"] = 0;
        }
        if (!("siteUrl" in $$source)) {
            this["siteUrl"] = "";
        }
        if (!("remoteId" in $$source)) {
            this["remoteId"] = 0;
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EntryRemoteLink instance from a string or object.
     */
    static createFrom($$source: any = {}): EntryRemoteLink {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EntryRemoteLink($$parsedSource as Partial<EntryRemoteLink>);
    }
}

export class EntrySummary {
    "id": number;
    "title": string;
    "createdAt": string;
    "modifiedAt": string;

    /** Creates a new EntrySummary instance. */
    constructor($$source: Partial<EntrySummary> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }
        if (!("modifiedAt" in $$source)) {
            this["modifiedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EntrySummary instance from a string or object.
     */
    static createFrom($$source: any = {}): EntrySummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EntrySummary($$parsedSource as Partial<EntrySummary>);
    }
}

export class ProfileEntry {
    "uuid": string;
    "display_name"?: string;
    "created_at": string;

    /**
     * Salt is a random per-profile salt used with the user's passphrase
     * to derive the symmetric encryption key. It is not secret.
     */
    "salt"?: string;

    /**
     * small encrypted value used to check that the passphrase-derived key is correct when unlocking a profile.
     */
    "encrypted_verifier"?: string;

    /** Creates a new ProfileEntry instance. */
    constructor($$source: Partial<ProfileEntry> = {}) {
        if (!("uuid" in $$source)) {
            this["uuid"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProfileEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): ProfileEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProfileEntry($$parsedSource as Partial<ProfileEntry>);
    }
}

export class ProfileIndex {
    "version": number;
    "profiles": ProfileEntry[];

    /** Creates a new ProfileIndex instance. */
    constructor($$source: Partial<ProfileIndex> = {}) {
        if (!("version" in $$source)) {
            this["version"] = 0;
        }
        if (!("profiles" in $$source)) {
            this["profiles"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProfileIndex instance from a string or object.
     */
    static createFrom($$source: any = {}): ProfileIndex {
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("profiles" in $$parsedSource) {
            $$parsedSource["profiles"] = $$createField1_0($$parsedSource["profiles"]);
        }
        return new ProfileIndex($$parsedSource as Partial<ProfileIndex>);
    }
}

export class PushEntryResult {
    "localId": number;
    "remoteId": number;

    /**
     * posted or patched
     */
    "action": string;
    "type": string;

    /**
     * case: the entry returns 200 but the uploads error
     */
    "uploadWarnings"?: string[];

    /** Creates a new PushEntryResult instance. */
    constructor($$source: Partial<PushEntryResult> = {}) {
        if (!("localId" in $$source)) {
            this["localId"] = 0;
        }
        if (!("remoteId" in $$source)) {
            this["remoteId"] = 0;
        }
        if (!("action" in $$source)) {
            this["action"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PushEntryResult instance from a string or object.
     */
    static createFrom($$source: any = {}): PushEntryResult {
        const $$createField4_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("uploadWarnings" in $$parsedSource) {
            $$parsedSource["uploadWarnings"] = $$createField4_0($$parsedSource["uploadWarnings"]);
        }
        return new PushEntryResult($$parsedSource as Partial<PushEntryResult>);
    }
}

export class StoredUpload {
    "id": number;
    "entryId": number;
    "realName": string;
    "hash": string;
    "hashAlgorithm": string;
    "filesize": number;
    "state": string;
    "createdAt": string;
    "modifiedAt": string;

    /** Creates a new StoredUpload instance. */
    constructor($$source: Partial<StoredUpload> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("entryId" in $$source)) {
            this["entryId"] = 0;
        }
        if (!("realName" in $$source)) {
            this["realName"] = "";
        }
        if (!("hash" in $$source)) {
            this["hash"] = "";
        }
        if (!("hashAlgorithm" in $$source)) {
            this["hashAlgorithm"] = "";
        }
        if (!("filesize" in $$source)) {
            this["filesize"] = 0;
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }
        if (!("modifiedAt" in $$source)) {
            this["modifiedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StoredUpload instance from a string or object.
     */
    static createFrom($$source: any = {}): StoredUpload {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StoredUpload($$parsedSource as Partial<StoredUpload>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = ProfileEntry.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Array($Create.Any);
